version: 2.1

orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install 
      - checkout
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install      
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Front-End e2e
          command: |
            npm run frontend:e2e
      - run:
          name: Front-End test
          command: |
            npm run frontend:test
      - run:
          name: Back-End test
          command: |
            npm run backend:test
filters:
  branches:
    only:
     - main
      
